AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  Template for the SAM demo meetup micro service
Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    CodeUri: MeetupApi

Resources:
  PutAttendeeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java8
      Handler: demosam.meetup.AttendeeHandler::handleRequest
      Events:
        PutAttendee:
          Type: Api
          Properties:
            Path: /meetup
            Method: put
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Attendees
      Tracing: Active

  AttendeesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: Attendees
      PrimaryKey:
        Name: email
        Type: String
